# Generated by Django 5.0.6 on 2024-06-25 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='featured_product',
            new_name='featured_products',
        ),
    ]
