# Generated by Django 5.0.6 on 2024-06-25 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_featured_product_collection_featured_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='featured_products',
            new_name='featured_product',
        ),
    ]
